version: '3.8'

services:
  app:
    build: ./WorkerService
    container_name: image-processor-app
    user: 0:0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
    depends_on:
      - rabbitmq
      - minio
    volumes:
      - shared:/shared
    networks:
      - app-network
    
  

  webapi:
    build: ./ImageProcessingAPI
    container_name: image-processing-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBITMQ_HOST=rabbitmq
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false 
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
      - minio
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    networks:
      - app-network

  minio:
    container_name: minio
    restart: on-failure
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    expose:
      - "9000"
      - "9001"
    command: server /data --console-address ":9001"
    networks:
      - app-network

volumes:
  mq_data:
  minio-data:
  shared:

networks:
  app-network:
